### ISSUE TITLE
pin out for J5 and J6 headers

### ISSUE THREAD

**Issue by gtalusan** [D3Engineering/410c_camera_support#6]
Hello,

Is there a diagram or pin out for the camera mezzanine?

**Comment by jenslin** [comment]
Hello,

The schematics for the camera mezzanine board are in our quick start guide which is available on 96boards.org:

https://github.com/96boards/website/blob/master/_product/mezzanine/d3camera/files/D3Eng_DesignCore_CamMezzBoard_OV5640_QuickStart_Guide_v1.pdf

Regards,
Jason

**Comment by gtalusan** [comment]
Thanks for the quick reply.  Super helpful!
