### ISSUE TITLE
Secondary Sensor

### ISSUE THREAD

**Issue by loicpoulain** [D3Engineering/410c_camera_support#7]
Hello,

I'm currently working with upstream OV5640 driver in order to make the D3 mezzanine compatible with DB410 out of the box. If the OV5640 sensor works well on the first connector this is not the case for the second one. Indeed when communicating over I2C/CCI with the second sensor I get I2C I/O errors even if only one sensor is connected to the mezzanine (on the second connector). So I wonder what is the difference with the first connector (don't have the schematics), could it be a GPIO misconfiguration (enable 33, reset 28) or other hardware issue.... In your wiki, for you indicate that **ovti,use_cci** should not be set for secondary sensor (with your ov5640 driver), what is the reason behind that ?

Regards,

Temp tree:
https://git.linaro.org/people/loic.poulain/linux.git/log/?h=qcomlt-4.14-d3-mezzanine

**Comment by d3-sdunnington** [comment]
Hello,
MIPI port 0 uses the CCI interface but MIPI port 1 uses the BLSP/I2c6 interface.
The ovti,use_cci was a workaround to use the CCI port for the camera on kernel version 4.9, 17.04 release which didn't have the CCI as a stand alone driver.

Alternatively we are organizing our 18.01 support release soon.  The driver has been updated to use the mainline ov5640 driver.  It also uses the new CCI driver.  The device tree in the new version has Camera 0 connected to CCI and Camera 1 connect to BLSP6/I2C2.

**Comment by loicpoulain** [comment]
Thanks this definitely helps.
