### ISSUE TITLE
ov5460 not detected

### ISSUE THREAD

**Issue by disdi** [D3Engineering/410c_camera_support#8]
I am not able to detect ov5460 on booting   below image -
 https://github.com/D3Engineering/410c_camera_support/releases/download/D3%2FRELEASE%2FOV5640_QCOMLT_4.9_1.1.1/dragonboard410c-boot-linux-20170630-13.img.gz

linaro@linaro-alip:~$ lsmod | grep ov5460
ov5640                 32768  1

linaro@linaro-alip:~$ dmesg | grep ov5640
linaro@linaro-alip:~$ dmesg | grep ov5640
[    9.678665] ov5640 1-0078: ov5640_probe: Enter, i2c addr = 0x78
[    9.679132] ov5640 1-0078: Enable HIGH
[    9.691294] ov5640 1-0078: Reset LOW
[    9.706587] ov5640 1-0078: s_power 1
[    9.745688] ov5640 1-0078: Enable LOW
[    9.763578] ov5640 1-0078: Reset High
[    9.986911] ov5640 1-0078: ov5640_read_reg : read reg error -22 on address 0x78: reg=0x300a
[    9.988367] ov5640 1-0078: cound not read ID high
[    10.011851] ov5640 1-0078: s_power 0

linaro@linaro-alip:~$ media-ctl -p -d /dev/media1
Failed to enumerate /dev/media1 (-13)

Checked /proc./device-tree and I find all the device tree nodes are present which are part of below commit -

https://github.com/D3Engineering/linux_kernel_qcomlt/commit/6fdc4f41bf39c12fb41e6dce819593b7b554ea53

I am doubting that is ov5460 shipped to me is damaged.

**Comment by d3-sdunnington** [comment]
Can you verify the camera position and orientation to this picture?
![Camera Position](https://github.com/D3Engineering/410c_camera_support/wiki/images/camera_connection.png)

The ov5640 should be on J3/CSI-0.  The second position is on a different I2C bus and requires a device tree modification.

Also ensure that the orientation is correct.  The image shows the OV5640 ribbon cable bent back on itself.  Without the bend the camera module will extend beyond the top of the board.

**Comment by disdi** [comment]
![d3_mezzaine](https://user-images.githubusercontent.com/4300338/50622777-06e78e80-0f36-11e9-8c3d-d2b87c0aa3eb.jpeg)

As you can see, the sensor module is connected to J3 in the right orientation.

Let me know if you see anything is wrong ?
What further steps should I take ?

**Comment by jenslin** [comment]
Hello,

The connection looks correct.  If you have followed all of the steps listed in our user's guide and have confirmed that all connections are seated properly, then it is likely that the cause is defective hardware.  The next step would be to process a return/exchange with Arrow.

Regards,
Jason

**Comment by disdi** [comment]
Are there any test points on D3 Mezzanine board that I can probe for some Voltage / Current readings to further verify whether Mezzanine Board is at fault( or not connected properly) or only the Image Sensor ?

**Comment by jenslin** [comment]
Full schematics for the mezzanine board can be found here:

https://github.com/D3Engineering/410c_camera_support/blob/master/D3%20DesignCore%20Camera%20Mezzanine%20Board%20OV5640%20Quick%20Start%20Guide%20v1.pdf

**Comment by disdi** [comment]
I am able to get ov5460 detected and working now.

Not sure what was the issue earlier.
I disconnected the sensor and  probed the Test Points TP1, TP2, TP5 , TP6 and TP7.

After verifying I2C lines were up with TP1 and TP2 and CSI0 is powered from MCU via TP7, I reconnected the sensor and it got detected.

Closing the issue with one request-

Please provide ORCAD file or a searchable PDF file  of schematics for the mezzanine board so that reading and searching for connectors  and nets are easy.
